// The routes the invariants run against. When you add a page, add its route
// here, or the invariants stop covering it. Course pages are one template,
// so a course per gate outcome covers the shapes it renders; /applications/1/
// is the demo request a fresh database is seeded with.
export const ROUTES = [
  "/",
  "/readme/",
  "/guide/",
  "/demo/",
  "/courses/COMP6466/",
  "/courses/COMP6242/",
  "/courses/COMP8620/",
  "/courses/COMP7710/",
  "/courses/COMP6120/",
  "/courses/ENGN6627/",
  "/courses/MGMT7020/",
  "/courses/COMP8820/",
  "/courses/COMP6490/",
  "/courses/COMP8620/?year=2026",
  "/applications/",
  "/applications/1/",
  "/record/",
  "/plan/",
  "/enrolments/1/",
  "/enrolments/1/?mode=drop",
  "/overload/",
  "/overload/1/",
  "/overload/?course=COMP7710&year=2027&term=S1",
  "/login/",
  "/register/",
  "/verify/",
  "/account/",
  "/reviewer-access/",
  "/reviewer-demo/",
  "/email-test/",
  "/change-password/",
  "/forgot-password/",
  "/forgot-password/?mode=demo",
  "/demo-inbox/",
  "/login/?mode=demo",
  "/register/?mode=demo",
  "/catalogue/",
  "/catalogue/?kind=course&code=COMP6434&year=2027",
  "/catalogue/?kind=course&code=COMP8880&year=2027",
  "/catalogue/?kind=specialisation&code=ARTIF-SPEC&year=2027",
];
